stages:
  - lint
  - build
  - deploy

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

.default-cache: &default-cache
  before_script:
    - npm ci --cache .npm --prefer-offline

eslint:
  extends:
    - .default-cache
  stage: lint
  image: node:16-alpine
  script:
    - npm ci
    - npm run lint

prettier:
  extends:
    - .default-cache
  stage: lint
  image: node:16-alpine
  script:
    - npm ci
    - npm run check:format

build:
  stage: build
  image: node:16-alpine
  script:
    - npm run build
  artifacts:
    paths:
      - build
    expire_in: 1 week

deploy:
  stage: deploy
  script:
    - apt -qq update && apt -qqy install rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" | tr -d '\r' >> ~/.ssh/known_hosts
    - rsync -a --progress --human-readable --delete build/** deploy@$IP:~/realworld/public
