name: Deploy

on:
  workflow_run:
    workflows:
      - build
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        env:
          API_HOST: ${{ secrets.API_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ecdsa
          chmod 600 ~/.ssh/id_ecdsa
          ssh-keyscan -t ecdsa -H $API_HOST >> ~/.ssh/known_hosts

      - name: Download build artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          name: build
          path: build

      - name: Copy files to the server
        env:
          API_HOST: ${{ secrets.API_HOST }}
        run: |
          rsync -a --progress --human-readable --delete build/** deploy@$API_HOST:~/realworld/public
