name: Deploy

on:
  workflow_run:
    workflows:
      - build
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        env:
          IP: ${{ secrets.IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ecdsa
          chmod 600 ~/.ssh/id_ecdsa
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Copy files to the server
        run: |
          rsync -a --progress --human-readable --delete \
            --exclude-from '.gitignore'
            --exclude .gitignore
            --exclude .git
            --exclude public
            build/** deploy@IP:~/realworld/public
